from django.db import models

class SeccData(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    State = models.CharField(max_length=101)
    District = models.CharField(max_length=101)
    SubDistrict = models.CharField(max_length=101)
    No_HH = models.BigIntegerField(null=True, blank=True)
    TOT_P = models.BigIntegerField(null=True, blank=True)
    TOT_M = models.BigIntegerField(null=True, blank=True)
    TOT_F = models.BigIntegerField(null=True, blank=True)
    P_06 = models.BigIntegerField(null=True, blank=True)
    M_06 = models.BigIntegerField(null=True, blank=True)
    F_06 = models.BigIntegerField(null=True, blank=True)
    P_SC = models.BigIntegerField(null=True, blank=True)
    M_SC = models.BigIntegerField(null=True, blank=True)
    F_SC = models.BigIntegerField(null=True, blank=True)
    P_ST = models.BigIntegerField(null=True, blank=True)
    M_ST = models.BigIntegerField(null=True, blank=True)
    F_ST = models.BigIntegerField(null=True, blank=True)
    P_LIT = models.BigIntegerField(null=True, blank=True)
    M_LIT = models.BigIntegerField(null=True, blank=True)
    F_LIT = models.BigIntegerField(null=True, blank=True)
    P_ILL = models.BigIntegerField(null=True, blank=True)
    M_ILL = models.BigIntegerField(null=True, blank=True)
    F_ILL = models.BigIntegerField(null=True, blank=True)
    TOT_WORK_P = models.BigIntegerField(null=True, blank=True)
    TOT_WORK_M = models.BigIntegerField(null=True, blank=True)
    TOT_WORK_F = models.BigIntegerField(null=True, blank=True)
    MAINWORK_P = models.BigIntegerField(null=True, blank=True)
    MAINWORK_M = models.BigIntegerField(null=True, blank=True)
    MAINWORK_F = models.BigIntegerField(null=True, blank=True)
    MAIN_CL_P = models.BigIntegerField(null=True, blank=True)
    MAIN_CL_M = models.BigIntegerField(null=True, blank=True)
    MAIN_CL_F = models.BigIntegerField(null=True, blank=True)
    MAIN_AL_P = models.BigIntegerField(null=True, blank=True)
    MAIN_AL_M = models.BigIntegerField(null=True, blank=True)
    MAIN_AL_F = models.BigIntegerField(null=True, blank=True)
    MAIN_HH_P = models.BigIntegerField(null=True, blank=True)
    MAIN_HH_M = models.BigIntegerField(null=True, blank=True)
    MAIN_HH_F = models.BigIntegerField(null=True, blank=True)
    MAIN_OT_P = models.BigIntegerField(null=True, blank=True)
    MAIN_OT_M = models.BigIntegerField(null=True, blank=True)
    MAIN_OT_F = models.BigIntegerField(null=True, blank=True)
    MARGWORK_P = models.BigIntegerField(null=True, blank=True)
    MARGWORK_M = models.BigIntegerField(null=True, blank=True)
    MARGWORK_F = models.BigIntegerField(null=True, blank=True)
    MARG_CL_P = models.BigIntegerField(null=True, blank=True)
    MARG_CL_M = models.BigIntegerField(null=True, blank=True)
    MARG_CL_F = models.BigIntegerField(null=True, blank=True)
    MARG_AL_P = models.BigIntegerField(null=True, blank=True)
    MARG_AL_M = models.BigIntegerField(null=True, blank=True)
    MARG_AL_F = models.BigIntegerField(null=True, blank=True)
    MARG_HH_P = models.BigIntegerField(null=True, blank=True)
    MARG_HH_M = models.BigIntegerField(null=True, blank=True)
    MARG_HH_F = models.BigIntegerField(null=True, blank=True)
    MARG_OT_P = models.BigIntegerField(null=True, blank=True)
    MARG_OT_M = models.BigIntegerField(null=True, blank=True)
    MARG_OT_F = models.BigIntegerField(null=True, blank=True)
    MARGWORK_3_6_P = models.BigIntegerField(null=True, blank=True)
    MARGWORK_3_6_M = models.BigIntegerField(null=True, blank=True)
    MARGWORK_3_6_F = models.BigIntegerField(null=True, blank=True)
    MARG_CL_3_6_P = models.BigIntegerField(null=True, blank=True)
    MARG_CL_3_6_M = models.BigIntegerField(null=True, blank=True)
    MARG_CL_3_6_F = models.BigIntegerField(null=True, blank=True)
    MARG_AL_3_6_P = models.BigIntegerField(null=True, blank=True)
    MARG_AL_3_6_M = models.BigIntegerField(null=True, blank=True)
    MARG_AL_3_6_F = models.BigIntegerField(null=True, blank=True)
    MARG_HH_3_6_P = models.BigIntegerField(null=True, blank=True)
    MARG_HH_3_6_M = models.BigIntegerField(null=True, blank=True)
    MARG_HH_3_6_F = models.BigIntegerField(null=True, blank=True)
    MARG_OT_3_6_P = models.BigIntegerField(null=True, blank=True)
    MARG_OT_3_6_M = models.BigIntegerField(null=True, blank=True)
    MARG_OT_3_6_F = models.BigIntegerField(null=True, blank=True)
    MARGWORK_0_3_P = models.BigIntegerField(null=True, blank=True)
    MARGWORK_0_3_M = models.BigIntegerField(null=True, blank=True)
    MARGWORK_0_3_F = models.BigIntegerField(null=True, blank=True)
    MARG_CL_0_3_P = models.BigIntegerField(null=True, blank=True)
    MARG_CL_0_3_M = models.BigIntegerField(null=True, blank=True)
    MARG_CL_0_3_F = models.BigIntegerField(null=True, blank=True)
    MARG_AL_0_3_P = models.BigIntegerField(null=True, blank=True)
    MARG_AL_0_3_M = models.BigIntegerField(null=True, blank=True)
    MARG_AL_0_3_F = models.BigIntegerField(null=True, blank=True)
    MARG_HH_0_3_P = models.BigIntegerField(null=True, blank=True)
    MARG_HH_0_3_M = models.BigIntegerField(null=True, blank=True)
    MARG_HH_0_3_F = models.BigIntegerField(null=True, blank=True)
    MARG_OT_0_3_P = models.BigIntegerField(null=True, blank=True)
    MARG_OT_0_3_M = models.BigIntegerField(null=True, blank=True)
    MARG_OT_0_3_F = models.BigIntegerField(null=True, blank=True)
    NON_WORK_P = models.BigIntegerField(null=True, blank=True)
    NON_WORK_M = models.BigIntegerField(null=True, blank=True)
    NON_WORK_F = models.BigIntegerField(null=True, blank=True)

    
    def __str__(self):
        return f'{self.State}, {self.District}, {self.SubDistrict}'
