def getTable(pdfDocument, siteData, sitePricing):
    pdfDocument.set_font('Arial', '', 14)
    pdfDocument.set_xy(300, 50)
    
    pdfDocument.cell(100, 25, "State")
    pdfDocument.cell(150, 25, siteData['state'])
    pdfDocument.cell(100, 25, "Display cost")
    pdfDocument.cell(150, 25, f"INR {str(sitePricing["cost_monthly"])}")
    pdfDocument.set_xy(300, 75)
    pdfDocument.cell(100, 25, "District")
    pdfDocument.cell(150, 25, siteData['district'])
    pdfDocument.cell(100, 25, "Printing cost")
    pdfDocument.cell(150, 25, f"INR {str(sitePricing["printing_cost"])}")
    pdfDocument.set_xy(300, 100)
    pdfDocument.cell(100, 25, "Area")
    pdfDocument.cell(150, 25, siteData['priorityArea'])
    pdfDocument.cell(100, 25, "Mounting cost")
    pdfDocument.cell(150, 25, f"INR {str(sitePricing["mounting_cost"])}")
    pdfDocument.set_xy(300, 125)
    pdfDocument.cell(100, 25, "Lat/Long")
    pdfDocument.cell(150, 25, str(round(siteData['site_lat'],4)) +" / "+str(round(siteData['site_long'],4)))
    pdfDocument.cell(100, 25, "Base Cost")
    pdfDocument.cell(150, 25, f"INR {str(sitePricing["mounting_cost"]+sitePricing["printing_cost"]+sitePricing["cost_monthly"])}")
    pdfDocument.set_xy(300, 150)
    pdfDocument.cell(100, 25, "Type")
    pdfDocument.cell(150, 25, siteData['media'])
    pdfDocument.cell(100, 25, "Tax @ 18%")
    pdfDocument.cell(150, 25, f"INR {str(round((sitePricing["mounting_cost"]+sitePricing["printing_cost"]+sitePricing["cost_monthly"])*.18,0))}")
    pdfDocument.set_xy(300, 175)
    pdfDocument.cell(100, 25, "Size")
    pdfDocument.cell(150, 25, f"W-{str(siteData['size_width'])}, H-{str(siteData['size_height'])}")
    pdfDocument.cell(100, 25, "Total Cost")
    pdfDocument.cell(150, 25, f"INR {str(sitePricing["mounting_cost"]+sitePricing["printing_cost"]+sitePricing["cost_monthly"] + round((sitePricing["mounting_cost"]+sitePricing["printing_cost"]+sitePricing["cost_monthly"])*.18,0))}")